### PR TITLE
Fix all shebangs to be os and python3 version agnostic

### PR DESCRIPTION
**Pull request by gavinfernandes2012**

### CODE REVIEW

**Comment by GarryMorrison** [comment]
thanks. Though most of them don't need a shebang line.

**Comment by gavinfernandes2012** [comment]
Yeah, exe's just tick me off though. I don't use windows at all.

**Comment by gavinfernandes2012** [comment]
Do you want me removing any useless shebangs before merge?

**Comment by GarryMorrison** [comment]
yup.

**Comment by gavinfernandes2012** [comment]
We should be able to merge this now

**Pull request merged**
