### PR TITLE
[WIP] Packaging

### PR DESCRIPTION
**Pull request by gavinfernandes2012**

### CODE REVIEW

**Comment by GarryMorrison** [comment]
Yup, it is fine to swap to agg backend.
Use this to test matplotlib still works:
```
plot rank split |a b c d e>
```

As for my tests, "comprehensive" is just another way of saying everything is all stuffed in together. It is not as comprehensive as it claims :). Feel free to go ahead with improvements to it.

A comment on the 11 failing tests:
test_compiler_simple_op_bracket_1
Given:
```
op1 |*> #=> |op1:> __ |_self>
```
we have:
```
sa: op1 (|x> + |y>)
|op1: x> + |op1: y>

sa: op1(|x> + |y>)
|>
```
This is probably not a bug, and is probably doing what we want it to do, since op1 is an operator not a sequence function.
Contrast it with the sequence function:
```
fn (*) #=> |fn:> __ |_self>

sa: fn (|x> + |y>)
|fn: x> + |fn: y>

sa: fn(|x> + |y>)
|fn: x> + |fn: y>

```

test_buggy_merge
Is a real bug! I don't know where exactly the bug originates from. Probably difficult to solve!
This fails:
```
|1> __ (|a> + |b> + |c>) + |2> __ (|d> + |e> + |f>)
```
since we expect the result to be:
```
|1 a> + |1 b> + |1 c> + |2 d> + |2 e> + |2 f>
```
but instead get:
```
3|1 a> + 3|1 b> + 3|1 c> + |2 d> + |2 e> + |2 f>
```
But in contrast, add in some brackets and this works as desired:
```
(|1> __ (|a> + |b> + |c>)) + (|2> __ (|d> + |e> + |f>))
```


test_tuple_op_4_bracket_op
Is probably not a bug. Depends on if we require a space between an operator and a bracket, and I think the answer should be yes.
So, we want this to fail and hence return |>, since op5 is an operator not a sequence function:
```
op5((- op4 + op3 __ op2 . op1)) |x>
```
And this to work:
```
op5 ((- op4 + op3 __ op2 . op1)) |x>
```

test_bracket_ops_merge_2
test_bracket_ops_merge_3
Ignore for now.

test_extract_compound_sequence_empty_learn_2
test_extract_compound_sequence_empty_learn_3
test_extract_compound_sequence_empty_learn_5
test_extract_compound_sequence_empty_learn_6
Are all real bugs. For some reason the leading |> is being chomped from sequences.
Again, probably difficult to solve.

test_self_insert_5
Doesn't look like a bug to me, and should be removed, given that this works correctly:
```
foo5 (*) #=> 29|_self0>

sa: foo5(|a>) |x>
29|x>

```

As for setup.py, garry@semantic-db.org is probably fine for the email, and I'm not sure write-up.semantic-db.org is the best url. That page hasn't seen any attention in a long time. Maybe leave it blank until I finish the documentation, or set it to http://semantic-db.org/documentation/usage/index.html.

**Comment by gavinfernandes2012** [comment]
How do you feel about moving the sdb_console.py ==> semantic_db/__main__.py ?
It would allow us to simply python3 -m semantic_db from anywhere to start the console.

I was working on it, but I've hit a roadblock with all the `from something import *` (!!!), so currently I can't seem to figure out where the `context` variable comes from. D'you remember where you got it from?

**Comment by gavinfernandes2012** [comment]
Alright, I'll add your email and change the documentation in setup.py now, and I'll switch over the mpl backend in a later commit.

**Comment by GarryMorrison** [comment]
context is in the parser section, just near the parsley grammar.
Just search for "bindings_dictionary" in code.py.
Indeed, the bindings dictionary is the reason for the "one global context" bug I have mentioned a couple of times. 

I guess main.py is fine for the console.

**Pull request merged**
