### PR TITLE
implemented command-line invoke

### PR DESCRIPTION
**Pull request by GarryMorrison**
is this what we had in mind?

### CODE REVIEW

**Comment by GarryMorrison** [comment]
Example:
```
$ ./sdb-console.py temperature-conversion.sw print-temperature-table.sw
Welcome to version 2 of the Semantic DB!
Last updated 24 August, 2018
+-----+-------+--------+
| C   | F     | K      |
+-----+-------+--------+
| 0   | 32.0  | 273.15 |
| 5   | 41.0  | 278.15 |
| 10  | 50.0  | 283.15 |
| 15  | 59.0  | 288.15 |
| 20  | 68.0  | 293.15 |
| 25  | 77.0  | 298.15 |
| 30  | 86.0  | 303.15 |
| 35  | 95.0  | 308.15 |
| 40  | 104.0 | 313.15 |
| 45  | 113.0 | 318.15 |
| 50  | 122.0 | 323.15 |
| 55  | 131.0 | 328.15 |
| 60  | 140.0 | 333.15 |
| 65  | 149.0 | 338.15 |
| 70  | 158.0 | 343.15 |
| 75  | 167.0 | 348.15 |
| 80  | 176.0 | 353.15 |
| 85  | 185.0 | 358.15 |
| 90  | 194.0 | 363.15 |
| 95  | 203.0 | 368.15 |
| 100 | 212.0 | 373.15 |
+-----+-------+--------+


sa:

```

**Comment by gavinfernandes2012** [comment]
Yeah that's exactly what I was thinking of, damn that was quick.

We can also probably add another PR to expand our test suite so that we have multiple tests using several scripts for which we know what the output should be. If the output is correct we pass the test, otherwise, we fail. I guess you can go ahead and merge this (unless you haven't finished) and I'll update my branches with the changes.

**Comment by GarryMorrison** [comment]
I have some tweaks in mind. First I have to remove some print statements, then I am going to rewrite it using getopt: https://docs.python.org/3.1/library/getopt.html
This will make it easier to add more command line options going forward.

**Comment by gavinfernandes2012** [comment]
Sure thing. If you ever do need to rewrite the implementation, there is a package called cmd2 that we can use to sorta outsource most of the command line functionality that you might need to implement. Just wanted to let you know in case its useful.

**Comment by gavinfernandes2012** [comment]
Also, for the unit tests, a way to disable the millisecond count would be very useful, unless we want to manually parse the output to find out if its correct.

**Comment by GarryMorrison** [comment]
Sure, we could add an option to switch off displaying run times. I was also thinking of -q and/or --quit, which doesn't print the welcome message, and drops back to the command line rather than the console.

**Comment by GarryMorrison** [comment]
Well, once I do the getopt thing, it will be easy to change as needed. How about -e and --exit then? Or do you have other recommendations?

**Comment by gavinfernandes2012** [comment]
I'll need a while to think about it, I'm going to head out to work now.

**Comment by gavinfernandes2012** [comment]
What I'm in favour of is specifying two options:
-q for quiet, to silence the timing output
-i for interactive to run a sdb script and drop to the sdb command line
Without -i, if we run a script, it should run the script and drop the user back to bash, not the sdb shell

This behaviour should feel familiar to most bash, zsh, fish shell and python interpreter users.
What do you say?

**Comment by GarryMorrison** [comment]
yup, fine by me. I'll get to that after some morning coffee.

**Comment by GarryMorrison** [comment]
I had a quick skim of cmd2, and my initial impression is that it is not a good fit.

**Comment by GarryMorrison** [comment]
Any interest in a 'dump' option? Perhaps -d and --dump?
ie, run given scripts, then do a context.print_multiverse().

**Comment by GarryMorrison** [comment]
```
$ ./sdb-console.py --version
Semantic DB 2.0
```

**Comment by gavinfernandes2012** [comment]
Looks great, I'm all for it. As long as tests are all running fine and all the options have been tested sufficiently, we shouldn't have any problems with this. (One of the reasons I wanted to write _unit_ tests was to be able to, (duh) automate testing, future PR idea for me)

**Comment by GarryMorrison** [comment]
Yup. Tested the options.
Last little thing, do we want this code or not?
```
# not sure we want this:
if len(files_to_run) == 0:
    interactive = True
```

**Comment by gavinfernandes2012** [comment]
Yeah I think that lines up pretty well with how bash et al behave, so I'm in favour of it

**Pull request merged**
