### PR TITLE
implement a config file

### PR DESCRIPTION
**Pull request by GarryMorrison**

### CODE REVIEW

**Comment by GarryMorrison** [comment]
Here are our current config options:
```
shell-history-length = 1000
save-shell-history = False
load-shell-history = True
shell-history-location = '.'
shell-history-filename = 'sdb-history.txt'
create-sw-directory-on-startup = False
create-dot-directory-on-startup = False
sw-directory = '.'
dot-directory = '.'
quiet-mode = False
logging-level = 'warning'
save-table = True
save-matrix = False
save-table-filename = 'saved-table.txt'
save-matrix-filename = 'saved-matrix.txt'
```
And we store it in $HOME/.sdb/config
All but the last four are implemented, and seem to be working.

**Comment by GarryMorrison** [comment]
@gavinfernandes2012 do you like these default values, and are there other config options we should add?

**Comment by GarryMorrison** [comment]
ok. I have the basics in place.

**Comment by GarryMorrison** [comment]
"shell-history-length" is not currently used in save-history.
Instead, it appends without limit.
We need to fix this at some stage.

**Comment by gavinfernandes2012** [comment]
Okay regarding history, would it be fine if we subclass list. That way we can redefine append to pop off the first line and then append, if the history is at its maximum length.
So every time `append(...)` is called, we do:

`python3
if len(self) > hist_len_lim:
    self.pop(0)
    super.append(self, ...)
`
At least I think that's how you write it.

And we can have the constructor of our new class take the history length as an argument

**Comment by GarryMorrison** [comment]
I don't know how to subclass a list....
And do we really need it? Can't we just do:
```
command_history.append(...)
command_history = command_history[-shell_history_length:]
```
The real issue is the saving history to file. Go have a look at the current version of save_history() in the shell. Though I think I have an idea of a better way to write that function. The problem is we need to load history from file, find its length, then append the current history, then write that back out.

**Comment by gavinfernandes2012** [comment]
Your call on whether we subclass or not.
Benefits of subclassing in this case: 
- You only change/add code in one location (easier to maintain)
- You don't need to remember to slice history every time you manipulate it

Benefits of just slicing:
- Simple
- Does litter the code with slices at multiple lines, doing the same thing


Anyways, how do you want to rewrite the file? What issues does the current implementation have?

**Comment by GarryMorrison** [comment]
Let's just slice. We only really need to do it in one location anyway.
Line 465 (in my code):
```
    command_history.append(line)
```

**Comment by gavinfernandes2012** [comment]
Wait a second, do we want to limit the command history in memory as well? or only on disk? I was assuming we wanted it to be 1000 lines in memory as well.

**Comment by GarryMorrison** [comment]
Both, though it would be a lot of work to hit 1000 lines in memory :).

**Comment by GarryMorrison** [comment]
Also relevant is this config line:
```
shell-history-display-length = 40
```
for the 'i' and 'history' command we use this number to limit how many lines we display.

**Comment by gavinfernandes2012** [comment]
1000 lines in memory seems doable considering we can load sw files and will soon be able to run scripts. And we'll have to slice in two places won't we? One where we load our "sw files to run" and one in the interactive agent.

**Comment by GarryMorrison** [comment]
Yeah, you can add it just after this line too if you like:
```
command_history.append('load ' + full_name)
```

**Comment by GarryMorrison** [comment]
How many lines of code do you think it would be? It would only be a win if it is only a handful.

**Comment by gavinfernandes2012** [comment]
I'm estimating only about 4 to 5 lines tops

**Comment by GarryMorrison** [comment]
OK then. If you want to write it, go ahead.

**Comment by GarryMorrison** [comment]
I'm tempted to change my mind on this one.
```
command_history.append(line)
```
is invoked every time you enter a line into the shell. If we correctly save out the right number of lines when we save history, I just don't see the in memory history length being more than a couple of lines longer than our desired length. I think we should put in the slicing here, and that should be sufficient.

**Comment by GarryMorrison** [comment]
As the commit statement says, I went ahead and implemented a new save_history() that respects our shell-history-length setting.

**Comment by gavinfernandes2012** [comment]
Alright, so are we moving forward without subclasses?

**Comment by GarryMorrison** [comment]
Yup. Just felt like over-kill.

**Comment by GarryMorrison** [comment]
@gavinfernandes2012 so, are we ready to merge this?

**Comment by gavinfernandes2012** [comment]
No this looks good to me, skimmed through the code as best I can

**Pull request merged**
